account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('api/', include('account.api.urls')),
    path('signin/', views.signin, name='signin'),
    path('orders/', views.orders, name='orders'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('addresses/', views.wishlist, name='addresses'),
]

electronics_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

orders/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('edit-cart/', views.edit_cart, name='api_edit_cart'),
    path('update-cart/', views.update_cart, name='api_update_cart'),
    path('update-draft-order/', views.update_draft_order, name='api_update_draft_order'),
    path('edit-wishlist/', views.edit_wishlist, name='api_edit_wishlist'),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('api/', include('orders.api.urls')),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout_details, name='checkout_details'),
    path('checkout/shipping/', views.checkout_shipping, name='checkout_shipping'),
    path('checkout/payment/', views.checkout_payment, name='checkout_payment'),
    path('checkout/review/', views.checkout_review, name='checkout_review'),
    path('checkout/complete/<int:order_id>', views.checkout_complete, name='checkout_complete'),
    path('order-tracking/<int:order_id>', views.order_tracking, name='order_tracking'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('<str:slug>/', views.product, name='product'),
    path('', views.products, name='products'),
]

orders/models.py
from django.db import models
from products.models import Product, ProductVariant
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.validators import MinValueValidator, MaxValueValidator

class PromoCode(models.Model):
    code = models.CharField(max_length=255)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    description = models.TextField(max_length=2550, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

class ShippingMethod(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=2550, blank=True, null=True)
    delivery_time = models.CharField(max_length=255)
    fee = models.IntegerField()

    def __str__(self):
        return self.name

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    shipping_method = models.ForeignKey(to=ShippingMethod, on_delete=models.PROTECT, null=True, blank=True)
    payment_method = models.CharField(max_length=255, choices=[('COD', 'COD'), ('Card', 'Card'), ('Paypal', 'Paypal')], null=True, blank=True)
    status = models.IntegerField(choices=[(-1, 'Draft'), (0, 'Created'), (1, 'Completed')])
    comment = models.TextField(max_length=2550, null=True, blank=True)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    promo_code = models.ForeignKey(to=PromoCode, on_delete=models.PROTECT, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'#{self.pk} {self.user.username}'

    def total_amount(self):
        total_amount = 0
        order_items = self.orderitem_set.all() # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            total_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        if self.status == -1:
            discount = self.promo_code.discount if self.promo_code else 0
        else:
            discount = self.discount or 0

        total_amount = round(total_amount * (1 - discount))
        total_amount += self.shipping_method.fee if self.shipping_method else 0

        return total_amount

    def subtotal_amount(self):
        subtotal_amount = 0
        order_items = self.orderitem_set.all()  # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            subtotal_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        return subtotal_amount

    def total_items(self):
        return self.orderitem_set.all().aggregate(Sum('quantity')).get('quantity__sum') or 0


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order {self.order.pk} {self.product_variant.product.name} {self.product_variant.version} {self.product_variant.color}'

    def amount(self):
        return self.quantity * (self.product_variant.price if self.order.status == -1 else (self.price or 0))

class Wishlist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product_variant')

    def __str__(self):
        return f'{self.user.username} {self.product_variant.product.name} {self.product_variant.version.name} {self.product_variant.color.name}'

orders/api/views.py
from django.db.models import Sum
from rest_framework import status, permissions, authentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response

from products.models import ProductVariant
from .serializers import OrderSerializer
from ..models import Order, OrderItem, Wishlist


def get_cart_info(order):
    order_items = OrderItem.objects.filter(order=order).all()

    data = {
        'total_items': order_items.aggregate(Sum('quantity')).get('quantity__sum') or 0,
        'total_amount': order.total_amount(),
        'items': order_items.values(),
    }

    for item in data['items']:
        product_variant = ProductVariant.objects.get(pk=item['product_variant_id'])

        item['product_variant'] = {
            'version': product_variant.version.name,
            'color': {
                'color_name': product_variant.color.name,
                'color_code': product_variant.color.color_code,
                'color_image': product_variant.color.color_image or None,
            },
            'price': product_variant.price
        }

        product = product_variant.product

        item['product'] = {
            'name': product.name,
            'slug': product.slug,
            'image': product.image.url
        }

    return data


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def edit_cart(request):
    payload = request.data
    action = payload.get('action')
    product_variant_id = payload.get('product_variant_id')
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_item, created = OrderItem.objects.get_or_create(order=order,
                                                          product_variant_id=product_variant_id)

    if action == 'add':
        order_item.quantity = order_item.quantity + 1 if order_item.quantity else 1
        # order_item.price = order_item.product_variant.price
        order_item.save()
    elif action == 'delete':
        order_item.delete()

    if order.orderitem_set.all().count() == 0:
        order.shipping_method = None
        order.promo_code = None
        order.save()

    data = get_cart_info(order)

    return Response(data=data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def update_cart(request):
    payload = request.data  # [{"product_variant_id": 1, "quantity": 3}, {"product_variant_id": 2, "quantity": 5}]

    order, created = Order.objects.get_or_create(user=request.user, status=-1)

    for item in payload:
        item, created = OrderItem.objects.get_or_create(order=order, product_variant_id=item[
            'product_variant_id'])

    order_items = OrderItem.objects.filter(order=order)

    for order_item in order_items:
        if order_item.product_variant.id in [item['product_variant_id'] for item in payload]:
            order_item.quantity = [item['quantity'] for item in payload if
                                   item['product_variant_id'] == order_item.product_variant.id][0]
            order_item.save()
        else:
            order_item.delete()

    if order.orderitem_set.all().count() == 0:
        order.shipping_method = None
        order.promo_code = None
        order.save()

    data = get_cart_info(order)

    return Response(data=data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def update_draft_order(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    payload = request.data

    data = OrderSerializer(order).data

    for field in payload:
        data[field] = payload[field]

    order_serializer = OrderSerializer(data=data)
    if order_serializer.is_valid():
        order_serializer.update(instance=order, validated_data=order_serializer.validated_data)

    return Response(data=order_serializer.data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def edit_wishlist(request):
    payload = request.data
    action = payload['action']
    product_variant_id = int(payload['product_variant_id'])

    if action == 'add':
        item, created = Wishlist.objects.get_or_create(user=request.user,
                                                       product_variant_id=product_variant_id)
    elif action == 'delete':
        item, created = Wishlist.objects.get_or_create(user=request.user,
                                                       product_variant_id=product_variant_id)
        item.delete()

    data = {
        'total_items': Wishlist.objects.filter(user=request.user).count()
    }

    return Response(data=data, status=status.HTTP_201_CREATED)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Order, OrderItem, ShippingMethod, PromoCode
# Create your views here.

@login_required
def cart(request):

    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)


    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items,
        'discounted_subtotal_amount': round(order.subtotal_amount() * (1- order.promo_code.discount)) if order.promo_code else 0
    }

    return render(request=request, template_name='orders/cart.html', context=context)

@login_required
def checkout_details(request):

    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/checkout/details.html', context=context)

@login_required
def checkout_shipping(request):
    shipping_methods = ShippingMethod.objects.all()
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'shipping_methods': shipping_methods,
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/shipping.html', context=context)

@login_required
def checkout_payment(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/payment.html', context=context)

@login_required
def checkout_review(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/review.html', context=context)

@login_required
def checkout_complete(request, order_id):
    order = Order.objects.get(pk=order_id)

    if order.status == -1:
        order.status = 0
        order.save()

        for order_item in order.orderitem_set.all():
            order_item.price = order_item.product_variant.price
            order_item.save()

    order_items = OrderItem.objects.filter(order=order)

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/checkout/complete.html', context=context)


def order_tracking(request, order_id):
    order = Order.objects.get(pk=order_id)
    order_items = OrderItem.objects.filter(order=order)

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/tracking.html', context=context)

orders/templates/orders/checkout/complete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Complete{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <div class="container pb-5 mb-sm-4">
        <div class="pt-5">
            <div class="card py-3 mt-sm-3">
                <div class="card-body text-center">
                    <h2 class="h4 pb-3">Thank you for your order!</h2>
                    <p class="fs-sm mb-2">Your order has been placed and will be processed as soon as possible.</p>
                    <p class="fs-sm mb-2">Make sure you make note of your order number, which is
                        <span class="fw-medium">{{ order.id }}</span>.</p>
                    <p class="fs-sm">You will be receiving an email shortly with confirmation of your order.
                        <u>You can now:</u></p><a class="btn btn-secondary mt-3 me-3"
                                                  href="{% url 'products:products' %}">Go back shopping</a><a
                        class="btn btn-primary mt-3" href="{% url 'orders:order_tracking' order.id %}"><i
                        class="ci-location"></i>&nbsp;Track order</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
{% endblock %}

orders/templates/orders/checkout/review.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Review{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
    <div class="page-title-overlap bg-dark pt-4">
        <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
            <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
                        <li class="breadcrumb-item"><a class="text-nowrap" href="/"><i
                                class="ci-home"></i>Home</a></li>
                        <li class="breadcrumb-item text-nowrap"><a
                                href="{% url 'orders:cart' %}">Cart</a>
                        </li>
                        <li class="breadcrumb-item text-nowrap active"
                            aria-current="page">Checkout
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
                <h1 class="h3 text-light mb-0">Checkout</h1>
            </div>
        </div>
    </div>

    <div class="container pb-5 mb-2 mb-md-4">
        <div class="row">
            <section class="col-lg-8">
                <!-- Steps-->
                <div class="steps steps-light pt-2 pb-3 mb-5"><a class="step-item active"
                                                                 href="{% url 'orders:cart' %}">
                    <div class="step-progress"><span class="step-count">1</span></div>
                    <div class="step-label"><i class="ci-cart"></i>Cart</div>
                </a><a class="step-item active" href="{% url 'orders:checkout_details' %}">
                    <div class="step-progress"><span class="step-count">2</span></div>
                    <div class="step-label"><i class="ci-user-circle"></i>Details</div>
                </a><a class="step-item active" href="{% url 'orders:checkout_shipping' %}">
                    <div class="step-progress"><span class="step-count">3</span></div>
                    <div class="step-label"><i class="ci-package"></i>Shipping</div>
                </a><a class="step-item active" href="{% url 'orders:checkout_payment' %}">
                    <div class="step-progress"><span class="step-count">4</span></div>
                    <div class="step-label"><i class="ci-card"></i>Payment</div>
                </a><a class="step-item active current" href="{% url 'orders:checkout_review' %}">
                    <div class="step-progress"><span class="step-count">5</span></div>
                    <div class="step-label"><i class="ci-check-circle"></i>Review</div>
                </a></div>
                <!-- Order details-->
                <h2 class="h6 pt-1 pb-3 mb-3 border-bottom">Review your order</h2>
                <!-- Item-->
                {% for order_item in order_items %}
                    <div class="d-sm-flex justify-content-between my-4 pb-3 border-bottom">
                        <div class="d-sm-flex text-center text-sm-start"><a
                                class="d-inline-block flex-shrink-0 mx-auto me-sm-4"
                                href="{% url 'products:product' order_item.product_variant.product.slug %}{{ order_item.product_variant.url_params }}"><img src="{{ order_item.product_variant.product.image.url }}" width="160"
                                                                alt="Product"></a>
                            <div class="pt-2">
                                <h3 class="product-title fs-base mb-2"><a
                                        href="{% url 'products:product' order_item.product_variant.product.slug %}{{ order_item.product_variant.url_params }}">{{ order_item.product_variant.product.name }}</a></h3>
                                <div class="fs-sm"><span class="text-muted me-2">Version:</span>{{ order_item.product_variant.version.name }}</div>
                                <div class="fs-sm"><span
                                        class="text-muted me-2">Color:</span>{{ order_item.product_variant.color.name }}
                                </div>
                                <div class="fs-lg text-accent pt-2">${{ order_item.product_variant.price }}</div>
                            </div>
                        </div>
                        <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-end"
                             style="max-width: 9rem;">
                            <p class="mb-0"><span
                                    class="text-muted fs-sm">Quantity: </span><span>{{ order_item.quantity }}</span></p>

                            <a href="{% url 'orders:cart' %}">
                                <button class="btn btn-link px-0" type="button">
                                    <i class="ci-edit me-2"></i><span class="fs-sm">Edit</span>
                                </button>
                            </a>
                        </div>
                    </div>
                {% endfor %}

                <!-- Client details-->
                <div class="bg-secondary rounded-3 px-4 pt-4 pb-2">
                    <div class="row">
                        <div class="col-sm-6">
                            <h4 class="h6">Shipping to:</h4>
                            <ul class="list-unstyled fs-sm">
                                <li><span class="text-muted">Client:&nbsp;</span>{{ order.full_name }}</li>
                                <li><span
                                        class="text-muted">Address:&nbsp;</span>{{ order.address }}
                                </li>
                                <li><span class="text-muted">Phone:&nbsp;</span>{{ order.phone }}
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-6">
                            <h4 class="h6">Shipping method:</h4>
                            <ul class="list-unstyled fs-sm">
                                <li><span class="text-muted">{{ order.shipping_method.name }}: </span> {{ order.shipping_method.delivery_time }}
                                </li>
                            </ul>

                            <h4 class="h6">Payment method:</h4>
                            <ul class="list-unstyled fs-sm">
                                <li><span class="text-muted">{{ order.payment_method }}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Navigation (desktop)-->
                <div class="d-none d-lg-flex pt-4">
                    <div class="w-50 pe-3"><a class="btn btn-secondary d-block w-100"
                                              href="{% url 'orders:checkout_payment' %}"><i
                            class="ci-arrow-left mt-sm-0 me-1"></i><span
                            class="d-none d-sm-inline">Back to Payment</span><span
                            class="d-inline d-sm-none">Back</span></a></div>
                    <div class="w-50 ps-2"><a class="btn btn-primary d-block w-100"
                                              href="{% url 'orders:checkout_complete' order.id %}"><span
                            class="d-none d-sm-inline">Complete order</span><span
                            class="d-inline d-sm-none">Complete</span><i
                            class="ci-arrow-right mt-sm-0 ms-1"></i></a></div>
                </div>
            </section>
            <!-- Sidebar-->
            <aside class="col-lg-4 pt-4 pt-lg-0 ps-xl-5">
                <div class="bg-white rounded-3 shadow-lg p-4 ms-lg-auto">
                    <div class="py-2 px-xl-2">
                        <h2 class="h6 text-center mb-4">Order summary</h2>
                        <ul class="list-unstyled fs-sm pb-2 border-bottom">
                            <li class="d-flex justify-content-between align-items-center"><span
                                    class="me-2">Subtotal:</span><span
                                    class="text-end">${{ order.subtotal_amount }}</span></li>
                            <li class="d-flex justify-content-between align-items-center"><span
                                    class="me-2">Shipping:</span><span class="text-end">{% if order.shipping_method %}$
                                {{ order.shipping_method.fee }}{% else %}—{% endif %}</span>
                            </li>

                            <li class="d-flex justify-content-between align-items-center"><span
                                    class="me-2">Discount:</span><span class="text-end">{% if order.promo_code %}{% widthratio order.promo_code.discount 1 100 %}%{% else %}—{% endif %}</span>
                            </li>
                        </ul>
                        <h3 class="fw-normal text-center my-4">${{ order.total_amount }}</h3>
                        <form class="needs-validation" method="post" novalidate="">
                            {% csrf_token %}
                            <div class="mb-3">
                                <input class="form-control" type="text" placeholder="Promo code"
                                       required="">
                                <div class="invalid-feedback">Please provide promo code.</div>
                            </div>
                            <button class="btn btn-outline-primary d-block w-100"
                                    type="submit">Apply promo code
                            </button>

                            {% if order.promo_code %}
                                <label class="form-label my-3" for="order-comment"><span
                                        class="badge bg-danger fs-xs me-2">-{% widthratio order.promo_code.discount 1 100 %}%</span><span
                                        class="fw-medium">Applied {{ order.promo_code.code }}</span></label>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </aside>
        </div>
        <!-- Navigation (mobile)-->
        <div class="row d-lg-none">
            <div class="col-lg-8">
                <div class="d-flex pt-4 mt-3">
                    <div class="w-50 pe-3"><a class="btn btn-secondary d-block w-100"
                                              href="{% url 'orders:checkout_payment' %}"><i
                            class="ci-arrow-left mt-sm-0 me-1"></i><span
                            class="d-none d-sm-inline">Back to Payment</span><span
                            class="d-inline d-sm-none">Back</span></a></div>
                    <div class="w-50 ps-2"><a class="btn btn-primary d-block w-100"
                                              href="{% url 'orders:checkout_complete' order.id %}"><span
                            class="d-none d-sm-inline">Complete order</span><span
                            class="d-inline d-sm-none">Complete</span><i
                            class="ci-arrow-right mt-sm-0 ms-1"></i></a></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
{% endblock %}