account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('api/', include('account.api.urls')),
    path('signin/', views.signin, name='signin'),
    path('orders/', views.orders, name='orders'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('addresses/', views.wishlist, name='addresses'),
]

electronics_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

orders/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('edit-cart/', views.edit_cart, name='api_edit_cart'),
    path('update-cart/', views.update_cart, name='api_update_cart'),
    path('update-draft-order/', views.update_draft_order, name='api_update_draft_order'),
    path('edit-wishlist/', views.edit_wishlist, name='api_edit_wishlist'),
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('api/', include('orders.api.urls')),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout_details, name='checkout_details'),
    path('checkout/shipping/', views.checkout_shipping, name='checkout_shipping'),
    path('checkout/payment/', views.checkout_payment, name='checkout_payment'),
    path('checkout/review/', views.checkout_review, name='checkout_review'),
    path('checkout/complete/<int:order_id>', views.checkout_complete, name='checkout_complete'),
    path('order-tracking/<int:order_id>', views.order_tracking, name='order_tracking'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('<str:slug>/', views.product, name='product'),
    path('', views.products, name='products'),
]

orders/models.py
from django.db import models
from products.models import Product, ProductVariant
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.validators import MinValueValidator, MaxValueValidator

class PromoCode(models.Model):
    code = models.CharField(max_length=255)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    description = models.TextField(max_length=2550, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

class ShippingMethod(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=2550, blank=True, null=True)
    delivery_time = models.CharField(max_length=255)
    fee = models.IntegerField()

    def __str__(self):
        return self.name

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    shipping_method = models.ForeignKey(to=ShippingMethod, on_delete=models.PROTECT, null=True, blank=True)
    payment_method = models.CharField(max_length=255, choices=[('COD', 'COD'), ('Card', 'Card'), ('Paypal', 'Paypal')], null=True, blank=True)
    status = models.IntegerField(choices=[(-1, 'Draft'), (0, 'Created'), (1, 'Completed')])
    comment = models.TextField(max_length=2550, null=True, blank=True)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    promo_code = models.ForeignKey(to=PromoCode, on_delete=models.PROTECT, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'#{self.pk} {self.user.username}'

    def total_amount(self):
        total_amount = 0
        order_items = self.orderitem_set.all() # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            total_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        if self.status == -1:
            discount = self.promo_code.discount if self.promo_code else 0
        else:
            discount = self.discount or 0

        total_amount = round(total_amount * (1 - discount))
        total_amount += self.shipping_method.fee if self.shipping_method else 0

        return total_amount

    def subtotal_amount(self):
        subtotal_amount = 0
        order_items = self.orderitem_set.all()  # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            subtotal_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        return subtotal_amount

    def total_items(self):
        return self.orderitem_set.all().aggregate(Sum('quantity')).get('quantity__sum') or 0


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order {self.order.pk} {self.product_variant.product.name} {self.product_variant.version} {self.product_variant.color}'

    def amount(self):
        return self.quantity * (self.product_variant.price if self.order.status == -1 else (self.price or 0))

class Wishlist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product_variant')

    def __str__(self):
        return f'{self.user.username} {self.product_variant.product.name} {self.product_variant.version.name} {self.product_variant.color.name}'

orders/api/views.py
from django.db.models import Sum
from rest_framework import status, permissions, authentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response

from products.models import ProductVariant
from .serializers import OrderSerializer
from ..models import Order, OrderItem, Wishlist


def get_cart_info(order):
    order_items = OrderItem.objects.filter(order=order).all()

    data = {
        'total_items': order_items.aggregate(Sum('quantity')).get('quantity__sum') or 0,
        'total_amount': order.total_amount(),
        'items': order_items.values(),
    }

    for item in data['items']:
        product_variant = ProductVariant.objects.get(pk=item['product_variant_id'])

        item['product_variant'] = {
            'version': product_variant.version.name,
            'color': {
                'color_name': product_variant.color.name,
                'color_code': product_variant.color.color_code,
                'color_image': product_variant.color.color_image or None,
            },
            'price': product_variant.price
        }

        product = product_variant.product

        item['product'] = {
            'name': product.name,
            'slug': product.slug,
            'image': product.image.url
        }

    return data


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def edit_cart(request):
    payload = request.data
    action = payload.get('action')
    product_variant_id = payload.get('product_variant_id')
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_item, created = OrderItem.objects.get_or_create(order=order,
                                                          product_variant_id=product_variant_id)

    if action == 'add':
        order_item.quantity = order_item.quantity + 1 if order_item.quantity else 1
        # order_item.price = order_item.product_variant.price
        order_item.save()
    elif action == 'delete':
        order_item.delete()

    if order.orderitem_set.all().count() == 0:
        order.shipping_method = None
        order.promo_code = None
        order.save()

    data = get_cart_info(order)

    return Response(data=data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def update_cart(request):
    payload = request.data  # [{"product_variant_id": 1, "quantity": 3}, {"product_variant_id": 2, "quantity": 5}]

    order, created = Order.objects.get_or_create(user=request.user, status=-1)

    for item in payload:
        item, created = OrderItem.objects.get_or_create(order=order, product_variant_id=item[
            'product_variant_id'])

    order_items = OrderItem.objects.filter(order=order)

    for order_item in order_items:
        if order_item.product_variant.id in [item['product_variant_id'] for item in payload]:
            order_item.quantity = [item['quantity'] for item in payload if
                                   item['product_variant_id'] == order_item.product_variant.id][0]
            order_item.save()
        else:
            order_item.delete()

    if order.orderitem_set.all().count() == 0:
        order.shipping_method = None
        order.promo_code = None
        order.save()

    data = get_cart_info(order)

    return Response(data=data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def update_draft_order(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    payload = request.data

    data = OrderSerializer(order).data

    for field in payload:
        data[field] = payload[field]

    order_serializer = OrderSerializer(data=data)
    if order_serializer.is_valid():
        order_serializer.update(instance=order, validated_data=order_serializer.validated_data)

    return Response(data=order_serializer.data, status=status.HTTP_201_CREATED)


@permission_classes([permissions.IsAuthenticated])
@authentication_classes([authentication.SessionAuthentication])
@api_view(['POST'])
def edit_wishlist(request):
    payload = request.data
    action = payload['action']
    product_variant_id = int(payload['product_variant_id'])

    if action == 'add':
        item, created = Wishlist.objects.get_or_create(user=request.user,
                                                       product_variant_id=product_variant_id)
    elif action == 'delete':
        item, created = Wishlist.objects.get_or_create(user=request.user,
                                                       product_variant_id=product_variant_id)
        item.delete()

    data = {
        'total_items': Wishlist.objects.filter(user=request.user).count()
    }

    return Response(data=data, status=status.HTTP_201_CREATED)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Order, OrderItem, ShippingMethod, PromoCode
# Create your views here.

@login_required
def cart(request):

    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)


    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items,
        'discounted_subtotal_amount': round(order.subtotal_amount() * (1- order.promo_code.discount)) if order.promo_code else 0
    }

    return render(request=request, template_name='orders/cart.html', context=context)

@login_required
def checkout_details(request):

    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/checkout/details.html', context=context)

@login_required
def checkout_shipping(request):
    shipping_methods = ShippingMethod.objects.all()
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'shipping_methods': shipping_methods,
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/shipping.html', context=context)

@login_required
def checkout_payment(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/payment.html', context=context)

@login_required
def checkout_review(request):
    order, created = Order.objects.get_or_create(user=request.user, status=-1)
    order_items = OrderItem.objects.filter(order=order)

    if request.method == 'POST':
        code = request.POST.get('promo_code')
        try:
            promo_code = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            promo_code = None

        if promo_code:
            order.promo_code = promo_code
            order.save()

    context = {
        'order': order,
        'order_items': order_items
    }
    return render(request=request, template_name='orders/checkout/review.html', context=context)

@login_required
def checkout_complete(request, order_id):
    order = Order.objects.get(pk=order_id)

    if order.status == -1:
        order.status = 0
        order.save()

        for order_item in order.orderitem_set.all():
            order_item.price = order_item.product_variant.price
            order_item.save()

    order_items = OrderItem.objects.filter(order=order)

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/checkout/complete.html', context=context)


def order_tracking(request, order_id):
    order = Order.objects.get(pk=order_id)
    order_items = OrderItem.objects.filter(order=order)

    context = {
        'order': order,
        'order_items': order_items
    }

    return render(request=request, template_name='orders/tracking.html', context=context)

orders/templates/orders/tracking.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Tracking{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}
<div class="bg-dark py-4">
        <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
          <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
                <li class="breadcrumb-item"><a class="text-nowrap" href="/"><i class="ci-home"></i>Home</a></li>
                <li class="breadcrumb-item text-nowrap"><a href="{% url 'account:orders' %}">Orders</a>
                </li>
                <li class="breadcrumb-item text-nowrap active" aria-current="page">Order tracking</li>
              </ol>
            </nav>
          </div>
          <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
            <h1 class="h3 text-light mb-0">Tracking order: <span class="h4 fw-normal text-light">{{ order.id }}</span></h1>
          </div>
        </div>
      </div>


<!-- Modal -->
<div class="modal fade" id="order-details" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Order No - {{ order.id }}</h5>
              <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body pb-0">
              <!-- Item-->
            {% for order_item in order_items %}
              <div class="d-sm-flex justify-content-between mb-4 pb-3 pb-sm-2 border-bottom">
                <div class="d-sm-flex text-center text-sm-start"><a class="d-inline-block flex-shrink-0 mx-auto" href="{% url 'products:product' order_item.product_variant.product.slug %}{{ order_item.product_variant.url_params }}" style="width: 10rem;"><img src="{{ order_item.product_variant.product.image.url }}" alt="Product"></a>
                  <div class="ps-sm-4 pt-2">
                    <h3 class="product-title fs-base mb-2"><a href="{% url 'products:product' order_item.product_variant.product.slug %}{{ order_item.product_variant.url_params }}">{{ order_item.product_variant.name }}</a></h3>
                    <div class="fs-sm"><span class="text-muted me-2">Version: </span>{{ order_item.product_variant.version.name }}</div>
                    <div class="fs-sm"><span class="text-muted me-2">Color: </span>{{ order_item.product_variant.color.name }}</div>
                    <div class="fs-lg text-accent pt-2">${{ order_item.price }}</div>
                  </div>
                </div>
                <div class="pt-2 ps-sm-3 mx-auto mx-sm-0 text-center">
                  <div class="text-muted mb-2">Quantity: </div>{{ order_item.quantity }}
                </div>
                <div class="pt-2 ps-sm-3 mx-auto mx-sm-0 text-center">
                  <div class="text-muted mb-2">Subtotal</div>${{ order_item.amount }}
                </div>
              </div>
            {% endfor %}


            </div>
            <!-- Footer-->
            <div class="modal-footer flex-wrap justify-content-between bg-secondary fs-md">
              <div class="px-2 py-1"><span class="text-muted">Subtotal:&nbsp;</span><span>${{ order.total_amount }}</span></div>
              <div class="px-2 py-1"><span class="text-muted">Shipping:&nbsp;</span><span>${{ order.shipping_method.fee }}</span></div>
              <div class="px-2 py-1"><span class="text-muted">Total:&nbsp;</span><span class="fs-lg">$297.<small>00</small></span></div>
            </div>
          </div>
        </div>
      </div>


<!-- Tracking -->
<div class="container py-5 mb-2 mb-md-3">
        <!-- Details-->
        <div class="row gx-4 mb-4">
          <div class="col-md-4 mb-2">
            <div class="bg-secondary h-100 p-4 text-center rounded-3"><span class="fw-medium text-dark me-2">Shipped via:</span>UPS Ground</div>
          </div>
          <div class="col-md-4 mb-2">
            <div class="bg-secondary h-100 p-4 text-center rounded-3"><span class="fw-medium text-dark me-2">Status:</span>Processing order</div>
          </div>
          <div class="col-md-4 mb-2">
            <div class="bg-secondary h-100 p-4 text-center rounded-3"><span class="fw-medium text-dark me-2">Expected date:</span>October 15, 2019</div>
          </div>
        </div>
        <!-- Progress-->
        <div class="card border-0 shadow-lg">
          <div class="card-body pb-2">
            <ul class="nav nav-tabs media-tabs nav-justified">
              <li class="nav-item">
                <div class="nav-link completed">
                  <div class="d-flex align-items-center">
                    <div class="media-tab-media"><i class="ci-bag"></i></div>
                    <div class="ps-3">
                      <div class="media-tab-subtitle text-muted fs-xs mb-1">First step</div>
                      <h6 class="media-tab-title text-nowrap mb-0">Order placed</h6>
                    </div>
                  </div>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link active">
                  <div class="d-flex align-items-center">
                    <div class="media-tab-media"><i class="ci-settings"></i></div>
                    <div class="ps-3">
                      <div class="media-tab-subtitle text-muted fs-xs mb-1">Second step</div>
                      <h6 class="media-tab-title text-nowrap mb-0">Processing order</h6>
                    </div>
                  </div>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                  <div class="d-flex align-items-center">
                    <div class="media-tab-media"><i class="ci-star"></i></div>
                    <div class="ps-3">
                      <div class="media-tab-subtitle text-muted fs-xs mb-1">Third step</div>
                      <h6 class="media-tab-title text-nowrap mb-0">Quality check</h6>
                    </div>
                  </div>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                  <div class="d-flex align-items-center">
                    <div class="media-tab-media"><i class="ci-package"></i></div>
                    <div class="ps-3">
                      <div class="media-tab-subtitle text-muted fs-xs mb-1">Fourth step</div>
                      <h6 class="media-tab-title text-nowrap mb-0">Product dispatched</h6>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
        <!-- Footer-->
        <div class="d-sm-flex flex-wrap justify-content-between align-items-center text-center pt-4">
          <div class="form-check mt-2 me-3">
            <input class="form-check-input" type="checkbox" id="notify-me" checked="">
            <label class="form-check-label" for="notify-me">Notify me when order is delivered</label>
          </div><a class="btn btn-primary btn-sm mt-2" href="#order-details" data-bs-toggle="modal">View Order Details</a>
        </div>
      </div>
{% endblock %}
{% block extra_js %}
{% endblock %}