account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    path('api/', include('account.api.urls')),
    path('signin/', views.signin, name='signin'),
    path('orders/', views.orders, name='orders'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('addresses/', views.wishlist, name='addresses'),
]

electronics_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home')
]

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('api/', include('orders.api.urls')),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout_details, name='checkout_details'),
    path('checkout/shipping/', views.checkout_shipping, name='checkout_shipping'),
    path('checkout/payment/', views.checkout_payment, name='checkout_payment'),
    path('checkout/review/', views.checkout_review, name='checkout_review'),
    path('checkout/complete/<int:order_id>', views.checkout_complete, name='checkout_complete'),
    path('order-tracking/<int:order_id>', views.order_tracking, name='order_tracking'),
]

orders/models.py
from django.db import models
from products.models import Product, ProductVariant
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.validators import MinValueValidator, MaxValueValidator

class PromoCode(models.Model):
    code = models.CharField(max_length=255)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    description = models.TextField(max_length=2550, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code

class ShippingMethod(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=2550, blank=True, null=True)
    delivery_time = models.CharField(max_length=255)
    fee = models.IntegerField()

    def __str__(self):
        return self.name

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    shipping_method = models.ForeignKey(to=ShippingMethod, on_delete=models.PROTECT, null=True, blank=True)
    payment_method = models.CharField(max_length=255, choices=[('COD', 'COD'), ('Card', 'Card'), ('Paypal', 'Paypal')], null=True, blank=True)
    status = models.IntegerField(choices=[(-1, 'Draft'), (0, 'Created'), (1, 'Completed')])
    comment = models.TextField(max_length=2550, null=True, blank=True)
    discount = models.FloatField(null=True, blank=True, default=0, validators=[MinValueValidator(0), MaxValueValidator(1)])
    promo_code = models.ForeignKey(to=PromoCode, on_delete=models.PROTECT, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'#{self.pk} {self.user.username}'

    def total_amount(self):
        total_amount = 0
        order_items = self.orderitem_set.all() # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            total_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        if self.status == -1:
            discount = self.promo_code.discount if self.promo_code else 0
        else:
            discount = self.discount or 0

        total_amount = round(total_amount * (1 - discount))
        total_amount += self.shipping_method.fee if self.shipping_method else 0

        return total_amount

    def subtotal_amount(self):
        subtotal_amount = 0
        order_items = self.orderitem_set.all()  # OrderItem.objects.filter(order=self)
        for order_item in order_items:
            subtotal_amount += order_item.quantity * (order_item.product_variant.price if self.status == -1 else (order_item.price or 0))

        return subtotal_amount

    def total_items(self):
        return self.orderitem_set.all().aggregate(Sum('quantity')).get('quantity__sum') or 0


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    price = models.IntegerField(null=True)
    quantity = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order {self.order.pk} {self.product_variant.product.name} {self.product_variant.version} {self.product_variant.color}'

    def amount(self):
        return self.quantity * (self.product_variant.price if self.order.status == -1 else (self.price or 0))

class Wishlist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.PROTECT)
    product_variant = models.ForeignKey(to=ProductVariant, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product_variant')

    def __str__(self):
        return f'{self.user.username} {self.product_variant.product.name} {self.product_variant.version.name} {self.product_variant.color.name}'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Cartzilla | Electronics Store{% endblock %}</title>
    <!-- SEO Meta Tags-->
    <meta name="description" content="Cartzilla - Bootstrap E-commerce Template">
    <meta name="keywords" content="bootstrap, shop, e-commerce, market, modern, responsive,  business, mobile, bootstrap, html5, css3, js, gallery, slider, touch, creative, clean">
    <meta name="author" content="Createx Studio">
    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon and Touch Icons-->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="mask-icon" color="#fe6a6a" href="safari-pinned-tab.svg">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendor Styles including: Font Icons, Plugins, etc.-->
    <link rel="stylesheet" media="screen" href="{% static 'vendor/simplebar/dist/simplebar.min.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/tiny-slider/dist/tiny-slider.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'vendor/drift-zoom/dist/drift-basic.min.css' %}"/>

    {% block extra_css %}{% endblock %}



    <!-- Main Theme Styles + Bootstrap-->
    <link rel="stylesheet" media="screen" href="{% static 'css/theme.min.css' %}">


</head>
<!-- Body-->
<body class="handheld-toolbar-enabled">
<!-- Sign in / sign up modal-->
{% if not request.user.is_authenticated %}
{% include 'signin_signup_modal.html' %}
{% endif %}

<main class="page-wrapper">
    <!-- Navbar Electronics Store-->
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
</main>
<!-- Footer-->
{% include 'footer.html' %}

<!-- Toolbar for handheld devices (Default)-->
<div class="handheld-toolbar">
    <div class="d-table table-layout-fixed w-100">
        <a class="d-table-cell handheld-toolbar-item" href="{% url 'account:wishlist' %}"><span class="handheld-toolbar-icon"><i class="ci-heart"></i></span><span
            class="handheld-toolbar-label">Wishlist</span></a>
        <a class="d-table-cell handheld-toolbar-item" href="javascript:void(0)" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                                                                 onclick="window.scrollTo(0, 0)"><span class="handheld-toolbar-icon"><i class="ci-menu"></i></span><span class="handheld-toolbar-label">Menu</span></a>
        <a class="d-table-cell handheld-toolbar-item" href="{% url 'orders:cart' %}">
            <span class="handheld-toolbar-icon">
                <i class="ci-cart"></i>
                <span class="badge bg-primary rounded-pill ms-1 total-items">
                    {% if request.user.is_authenticated %}
                        {% for order in  request.user.order_set.all %}
                            {% if order.status == -1 %}
                                {{ order.total_items }}
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        0
                    {% endif %}
                </span>
            </span>
            <span class="handheld-toolbar-label total-amount">
                {% if request.user.is_authenticated %}
                    {% for order in  request.user.order_set.all %}
                        {% if order.status == -1 %}
                            {{ order.total_amount }}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    0
                {% endif %}
            </span>
        </a>
    </div>
</div>


<!-- Back To Top Button--><a class="btn-scroll-top" href="#top" data-scroll><span class="btn-scroll-top-tooltip text-muted fs-sm me-2">Top</span><i class="btn-scroll-top-icon ci-arrow-up"> </i></a>
<!-- Vendor scrits: js libraries and plugins-->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/simplebar/dist/simplebar.min.js' %}"></script>
<script src="{% static 'vendor/tiny-slider/dist/min/tiny-slider.js' %}"></script>
<script src="{% static 'vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
<script src="{% static 'vendor/drift-zoom/dist/Drift.min.js' %}"></script>

{% block extra_js %}{% endblock %}

<!-- Main theme script-->
<script src="{% static 'js/theme.min.js' %}"></script>

<!-- Main app script -->
<script src="{% static 'js/app.js' %}"></script>
</html>

templates/blank_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block extra_css %}
{% endblock %}
{% block content %}

{% endblock %}
{% block extra_js %}
{% endblock %}

templates/footer.html
{% load static %}
<footer class="footer bg-dark pt-5">
    <div class="container">
        <div class="row pb-2">
            <div class="col-md-4 col-sm-6">
                <div class="widget widget-links widget-light pb-2 mb-4">
                    <h3 class="widget-title text-light">Shop departments</h3>
                    <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Sneakers &amp; Athletic</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Athletic Apparel</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Sandals</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Jeans</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Shirts &amp; Tops</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Shorts</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">T-Shirts</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Swimwear</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Clogs &amp; Mules</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Bags &amp; Wallets</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Accessories</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Sunglasses &amp; Eyewear</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Watches</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <div class="widget widget-links widget-light pb-2 mb-4">
                    <h3 class="widget-title text-light">Account &amp; shipping info</h3>
                    <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Your account</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Shipping rates &amp; policies</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Refunds &amp; replacements</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Order tracking</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Delivery info</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Taxes &amp; fees</a></li>
                    </ul>
                </div>
                <div class="widget widget-links widget-light pb-2 mb-4">
                    <h3 class="widget-title text-light">About us</h3>
                    <ul class="widget-list">
                        <li class="widget-list-item"><a class="widget-list-link" href="#">About company</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Our team</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">Careers</a></li>
                        <li class="widget-list-item"><a class="widget-list-link" href="#">News</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget pb-2 mb-4">
                    <h3 class="widget-title text-light pb-1">Stay informed</h3>
                    <form action="https://studio.us12.list-manage.com/subscribe/post?u=c7103e2c981361a6639545bd5&amp;amp;id=29ca296126" class="subscription-form validate" method="post"
                          name="mc-embedded-subscribe-form" novalidate="" target="_blank">
                        <div class="input-group flex-nowrap"><i class="ci-mail position-absolute top-50 translate-middle-y text-muted fs-base ms-3"></i>
                            <input class="form-control rounded-start" name="EMAIL" placeholder="Your email" required="" type="email"/>
                            <button class="btn btn-primary" name="subscribe" type="submit">Subscribe*</button>
                        </div>
                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div aria-hidden="true" style="position: absolute; left: -5000px;">
                            <input class="subscription-form-antispam" name="b_c7103e2c981361a6639545bd5_29ca296126" tabindex="-1" type="text"/>
                        </div>
                        <div class="form-text text-light opacity-50">*Subscribe to our newsletter to receive early discount offers, updates and new products info.</div>
                        <div class="subscription-status"></div>
                    </form>
                </div>
                <div class="widget pb-2 mb-4">
                    <h3 class="widget-title text-light pb-1">Download our app</h3>
                    <div class="d-flex flex-wrap">
                        <div class="me-2 mb-2"><a class="btn-market btn-apple" href="#" role="button"><span class="btn-market-subtitle">Download on the</span><span
                                class="btn-market-title">App Store</span></a></div>
                        <div class="mb-2"><a class="btn-market btn-google" href="#" role="button"><span class="btn-market-subtitle">Download on the</span><span
                                class="btn-market-title">Google Play</span></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pt-5 bg-darker">
        <div class="container">
            <div class="row pb-3">
                <div class="col-md-3 col-sm-6 mb-4">
                    <div class="d-flex"><i class="ci-rocket text-primary" style="font-size: 2.25rem;"></i>
                        <div class="ps-3">
                            <h6 class="fs-base text-light mb-1">Fast and free delivery</h6>
                            <p class="mb-0 fs-ms text-light opacity-50">Free delivery for all orders over $200</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 mb-4">
                    <div class="d-flex"><i class="ci-currency-exchange text-primary" style="font-size: 2.25rem;"></i>
                        <div class="ps-3">
                            <h6 class="fs-base text-light mb-1">Money back guarantee</h6>
                            <p class="mb-0 fs-ms text-light opacity-50">We return money within 30 days</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 mb-4">
                    <div class="d-flex"><i class="ci-support text-primary" style="font-size: 2.25rem;"></i>
                        <div class="ps-3">
                            <h6 class="fs-base text-light mb-1">24/7 customer support</h6>
                            <p class="mb-0 fs-ms text-light opacity-50">Friendly 24/7 customer support</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 mb-4">
                    <div class="d-flex"><i class="ci-card text-primary" style="font-size: 2.25rem;"></i>
                        <div class="ps-3">
                            <h6 class="fs-base text-light mb-1">Secure online payment</h6>
                            <p class="mb-0 fs-ms text-light opacity-50">We possess SSL / Secure сertificate</p>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="hr-light mb-5"/>
            <div class="row pb-2">
                <div class="col-md-6 text-center text-md-start mb-4">
                    <div class="text-nowrap mb-4"><a class="d-inline-block align-middle mt-n1 me-3" href="#"><img alt="Cartzilla" class="d-block" src="{% static 'img/footer-logo-light.png' %}"
                                                                                                                  width="117"/></a>
{#                        <div class="btn-group dropdown disable-autohide">#}
{#                            <button class="btn btn-outline-light border-light btn-sm dropdown-toggle px-2" data-bs-toggle="dropdown" type="button"><img alt="English" class="me-2"#}
{#                                                                                                                                                        src="{% static 'img/flags/en.png' %}"#}
{#                                                                                                                                                        width="20"/>Eng / $#}
{#                            </button>#}
{#                            <ul class="dropdown-menu my-1">#}
{#                                <li class="dropdown-item">#}
{#                                    <select class="form-select form-select-sm">#}
{#                                        <option value="usd">$ USD</option>#}
{#                                        <option value="eur">€ EUR</option>#}
{#                                        <option value="ukp">£ UKP</option>#}
{#                                        <option value="jpy">¥ JPY</option>#}
{#                                    </select>#}
{#                                </li>#}
{#                                <li><a class="dropdown-item pb-1" href="#"><img alt="Français" class="me-2" src="{% static 'img/flags/fr.png' %}" width="20"/>Français</a></li>#}
{#                                <li><a class="dropdown-item pb-1" href="#"><img alt="Deutsch" class="me-2" src="{% static 'img/flags/de.png' %}" width="20"/>Deutsch</a></li>#}
{#                                <li><a class="dropdown-item" href="#"><img alt="Italiano" class="me-2" src="{% static 'img/flags/it.png' %}" width="20"/>Italiano</a></li>#}
{#                            </ul>#}
{#                        </div>#}
                    </div>
                    <div class="widget widget-links widget-light">
                        <ul class="widget-list d-flex flex-wrap justify-content-center justify-content-md-start">
                            <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Outlets</a></li>
                            <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Affiliates</a></li>
                            <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Support</a></li>
                            <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Privacy</a></li>
                            <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Terms of use</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 text-center text-md-end mb-4">
                    <div class="mb-3"><a class="btn-social bs-light bs-twitter ms-2 mb-2" href="#"><i class="ci-twitter"></i></a><a class="btn-social bs-light bs-facebook ms-2 mb-2" href="#"><i
                            class="ci-facebook"></i></a><a class="btn-social bs-light bs-instagram ms-2 mb-2" href="#"><i class="ci-instagram"></i></a><a
                            class="btn-social bs-light bs-pinterest ms-2 mb-2" href="#"><i class="ci-pinterest"></i></a><a class="btn-social bs-light bs-youtube ms-2 mb-2" href="#"><i
                            class="ci-youtube"></i></a></div>
                    <img alt="Payment methods" class="d-inline-block" src="{% static 'img/cards-alt.png' %}" width="187"/>
                </div>
            </div>
            <div class="pb-4 fs-xs text-light opacity-50 text-center text-md-start">© All rights reserved. Made by <a class="text-light" href="https://createx.studio/" rel="noopener" target="_blank">Createx
                Studio</a></div>
        </div>
    </div>
</footer>

templates/page_title.html
<div class="page-title-overlap bg-dark pt-4">
    <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
        <div class="order-lg-2 mb-3 mb-lg-0 pt-lg-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-light flex-lg-nowrap justify-content-center justify-content-lg-start">
                    <li class="breadcrumb-item"><a class="text-nowrap" href="/"><i class="ci-home"></i>Home</a></li>
                    {% block breadcrumb %}
                    <li class="breadcrumb-item text-nowrap"><a href="#">Shop</a></li>
                    <li class="breadcrumb-item text-nowrap active" aria-current="page">Grid left sidebar</li>
                    {% endblock %}
                </ol>
            </nav>
        </div>
        <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
            <h1 class="h3 text-light mb-0">{% block page_title %}Shop grid left sidebar{% endblock %}</h1>
        </div>
    </div>
</div>

templates/signin_signup_modal.html
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-secondary">
                <ul class="nav nav-tabs card-header-tabs" role="tablist">
                    <li class="nav-item"><a class="nav-link fw-medium active" href="#signin-tab" data-bs-toggle="tab" role="tab" aria-selected="true"><i class="ci-unlocked me-2 mt-n1"></i>Sign in</a>
                    </li>
                    <li class="nav-item"><a class="nav-link fw-medium" href="#signup-tab" data-bs-toggle="tab" role="tab" aria-selected="false"><i class="ci-user me-2 mt-n1"></i>Sign up</a></li>
                </ul>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body tab-content py-4">
                <form class="needs-validation tab-pane fade show active" autocomplete="off" novalidate id="signin-tab" action="{% url 'account:signin' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="si-email">Username</label>
                        <input class="form-control" type="text" id="si-email" placeholder="Username" name="username" required>
                        <div class="invalid-feedback">Please provide a valid username.</div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="si-password">Password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="si-password" name="password" required>
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                            </label>
                        </div>
                    </div>
                    <div class="mb-3 d-flex flex-wrap justify-content-between">
                        <div class="form-check mb-2">
                            <input class="form-check-input" type="checkbox" id="si-remember">
                            <label class="form-check-label" for="si-remember">Remember me</label>
                        </div>
                        <a class="fs-sm" href="#">Forgot password?</a>
                    </div>
                    <button class="btn btn-primary btn-shadow d-block w-100" type="submit">Sign in</button> <!-- Change submit to button to avoid boostrap modal close after click -->
                </form>

                <form class="needs-validation tab-pane fade" autocomplete="off" novalidate id="signup-tab">
                    <div class="mb-3">
                        <label class="form-label" for="su-username">Username</label>
                        <input class="form-control" type="text" id="su-username" placeholder="johndoe" name="username" required>
                        <div class="invalid-feedback">Please fill in your username.</div>
                    </div>
                    <div class="mb-3">
                        <label for="su-email">Email address</label>
                        <input class="form-control" type="email" id="su-email" placeholder="johndoe@example.com" name="email" required>
                        <div class="invalid-feedback">Please provide a valid email address.</div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="su-password">Password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="su-password" name="password" required>
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                            </label>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="su-password-confirm">Confirm password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="su-password-confirm" required>
                            <label class="password-toggle-btn" aria-label="Show/hide password">
                                <input class="password-toggle-check" type="checkbox"><span class="password-toggle-indicator"></span>
                            </label>
                            <div class="invalid-feedback" id="password-mismatch">Confirm password is not match.</div>

                        </div>
                    </div>
                    <button class="btn btn-primary btn-shadow d-block w-100" type="submit">Sign up</button>
                </form>

                <div id="signup-status-alert" class="mt-5" style="display: none"></div>

            </div>
        </div>
    </div>
</div>